update: report vulnerability via github, not email
erlang/erlang-org pull request #155
Opened 2024-10-07 13:07 UTC by kikofernandez

This PR updates how users should report security vulnerabilities in Erlang/OTP.

I have added a deprecation note on the old post from 2017, remove references to emailing us security vulnerabilities (usually users do not encrypt these messages), and copy-pasted news/111 into news/172 removing also references to bugs.erlang.org (which points to https://github.com/erlang/otp/issues).

2024-10-07 13:31 UTC, frej commented on _news/172.md
> +system can affect the confidentiality, integrity and availability.
This sentence is incomplete. Also the standard phrase is "unprivileged user", so I would suggest:

"A general rule is that a bug which allows an unprivileged user to successfully attack the Erlang application, the Erlang runtime, or can be used as a springboard to attack other software running on the same or other machines is considered a security issue. As attacks we consider anything that affects the confidentiality, integrity and/or availability of the system."

2024-10-07 13:38 UTC, kikofernandez commented on _news/172.md
> +system can affect the confidentiality, integrity and availability.
solved, I think.
Thanks

2024-10-07 14:59 UTC, kikofernandez commented
I am not sure I understand what netlify is complaining about...
I have run `make test` locally and all seems to work, and I have run `make serve` and it looks ok.

2024-10-10 08:03 UTC, IngelaAndin commented on _news/172.md
> +
We should refer to GitHub secure issues here too, and get rid of the email-list in the long run I think.

2024-10-10 08:07 UTC, kikofernandez commented on _news/172.md
> +
solved :)

2024-10-10 08:49 UTC, u3s requested changes
I don't know how this security tab on github really works.
I think, I don't have enough privileges for handling the items properly.

There is some procedure behind handling those items on github, I would like to understand it before we change way of working with community.

2024-10-10 08:49 UTC, u3s commented on _news/172.md
> +Please use a descriptive email title for your report. After the initial response to your report, the security team will keep you updated on the progress and decision being made towards a fix and rele
what email?

2024-10-10 08:49 UTC, u3s commented on _news/172.md
> +If you believe that an existing public issue on [https://github.com/erlang/otp/issues](https://github.com/erlang/otp/issues) is security-related, we ask that you report it via [https://github.com/erl
what is ERL-001? some leftover from old days?

2024-10-10 12:35 UTC, kikofernandez commented on _news/172.md
> +Please use a descriptive email title for your report. After the initial response to your report, the security team will keep you updated on the progress and decision being made towards a fix and rele
good catch

2024-10-10 12:39 UTC, kikofernandez commented on _news/172.md
> +If you believe that an existing public issue on [https://github.com/erlang/otp/issues](https://github.com/erlang/otp/issues) is security-related, we ask that you report it via [https://github.com/erl
I took an example from `xmerl`. Please let me know if it does not look good, or if it is not a good example.
If you have any preferred way of writing this, let me know with a suggestion :)

2024-10-10 13:25 UTC, u3s commented on _news/172.md
> +If you believe that an existing public issue on [https://github.com/erlang/otp/issues](https://github.com/erlang/otp/issues) is security-related, we ask that you report it via [https://github.com/erl
ERL-001 is a sample identifier not used anymore? is it?
you intended to refer to github issue numer - maybe GH-001 is wanted?

2024-10-14 09:39 UTC, garazdawi commented
I pushed a fix to master for the redirect rules. If you rebase the PR, CI should now pass.

2024-10-14 09:42 UTC, garazdawi commented
It is quite simple to add a new page with the security information instead of a news item. We could then link from it from the downloads page?

2024-10-14 11:14 UTC, kikofernandez commented
Ok, I have added a new Security page in the header. But I can put some description in the Downloads and add it there.
I thought that the Security possibly deserves its own space to be visible everywhere to everyone.

Please, let me know if anyone disagrees, and propose change :)

2024-10-14 11:18 UTC, kikofernandez commented
also some other remaining part regarding news/172. I think I have finished that now

2024-10-14 11:49 UTC, garazdawi commented on security.md
> +Please follow this document in order to report security vulnerabilities in Erlang/OTP.
```suggestion
## Summary
Please create a new [Security Advisory](https://github.com/erlang/otp/security/advisories) for security issues. **Do not create a public github issue**.

Please follow this document in order to report security vulnerabilities in Erlang/OTP. 
```

Having a toddler at home has tought me that you should start with saying what you want someone to do, people always seem to miss the *not*.

2024-10-14 18:10 UTC, kikofernandez commented
@IngelaAndin and/or @u3s , I know there were concerns about using Github Securities, at least until Security Masters feel ok using it. Whenever that happens, let me know and I merge the PR :)

2024-10-25 15:12 UTC, kikofernandez commented
Given that we are discussing this PR soon, I also added a new file to indicate researchers how to tell us about vulnerabilities.
https://securitytxt.org/

This has been recommended by CISA, Nederland Gov, UK Gov, many Swedish websites (even H&M has one), Google, Facebook, Github, etc. It is something small that seems to serve a good purpose. I think we should add it, even if it means placing a ticket to as a reminder to renew the date.

2024-10-30 14:15 UTC, u3s commented on .well-known/security.txt
> +Expires: 2025-04-01T00:00:00z
requires a manual update every year.
supposed to be done manually or automatically on some frequent occasion.

pls update date to October/Nov?

2024-10-30 14:21 UTC, u3s commented on security.md
> +There is not any hard and fast rule to determine if a bug is worth reporting as a security issue to [https://github.com/erlang/otp/security](https://github.com/erlang/otp/security). A general rule is
Maybe remove link ?

2024-11-01 12:53 UTC, kikofernandez commented
Merging on Monday, 14:00 unless someone objects

2024-11-06 08:50 UTC, merged